apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-mgmt-backend-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emp-mgmt-backend-app
  template:
    metadata:
      labels:
        app: emp-mgmt-backend-app
    spec:
      initContainers:
      - name: init-logs-permission
        image: busybox
        command: ["sh", "-c", "mkdir -p /app/logs && chmod 777 /app/logs"]
        volumeMounts:
        - name: backend-logs-vol
          mountPath: /app/logs
      containers:
      - name: emp-mgmt-backend-container
        image: amritjsr/emp_mgmt_backend:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: backend-logs-vol
          mountPath: /app/logs
        # resources:
        #   requests:
        #     memory: "128Mi"
        #     cpu: "75m"
        #   limits:
        #     memory: "256Mi"
        #     cpu: "250m"
        env:
        # From ConfigMap
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: emp-mgmt-db-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: emp-mgmt-db-config
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: emp-mgmt-db-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: emp-mgmt-db-config
              key: DB_PORT

        # From Secret
        - name: DB_PASSWORD_ENCRYPTED
          valueFrom:
            secretKeyRef:
              name: emp-mgmt-db-password
              key: DB_PASSWORD_ENCRYPTED
      - name: promtail-sidecar
        image: grafana/promtail:latest
        args: ["-config.file=/etc/promtail/promtail.yaml"]
        volumeMounts:
        - name: backend-logs-vol
          mountPath: /app/logs
        - name: promtail-config-vol
          mountPath: /etc/promtail
      podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: emp-mgmt-backend-app
      volumes:
      - name: backend-logs-vol
        persistentVolumeClaim:
          claimName: backend-logs-pvc
      - name: promtail-config-vol
        configMap:
          name: promtail-sidecar-config