apiVersion: v1
kind: ConfigMap
metadata:
  name: emp-mgmt-backend-api-endpoint
  namespace: default
data:
  BACKEND_API_BASE_URL: "/api"
  BACKEND_SERVICE_URL: "http://emp-mgmt-backend-service:8080"
  BACKEND_API_HEALTH_URL: "http://emp-mgmt-backend-service:8080/api/health/"


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: emp-mgmt-db-config
  namespace: default
data:
  DB_NAME: employee_db
  DB_USER: emp_admin
  DB_HOST: 192.168.0.149
  DB_PORT: "3306"
